package com.project.SuperC.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.*; // Specific import for GenerationType

import lombok.Data; // Import for Lombok annotations

/**
 * Represents a user's price tracking request for a product.
 * This class is mapped to the "superc" table in the database.
 * Uses Lombok's @Data to automatically generate getters, setters,
 * equals(), hashCode(), and toString() methods.
 */
@Entity // Marks this class as a JPA entity, mapping it to a database table.
@Table(name = "superc") // Specifies the name of the database table.
@Data // Lombok annotation to auto-generate boilerplate code.
public class Request {

    /**
     * Unique identifier for the request.
     * This field is the primary key and its value is auto-generated by the database.
     */
    @Id // Marks this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures auto-incrementing ID.
    private int id;

    /**
     * The user's email address for notifications.
     * This field is unique and cannot be null, ensuring each user's email is distinct.
     */
    @Column(unique = true, nullable = false) // Configures column properties for email.
    private String email;

    /**
     * The unique product number for the item to be tracked.
     * Stored as a String to accommodate large numerical identifiers (e.g., UPC codes).
     */
    private String productNumber;

    /**
     * The maximum price the user is willing to pay for the product.
     * Notifications will be sent if the current price drops to or below this value.
     */
    private float maxPrice;
}